In [1]:
# https://pytorch.org/get-started/locally/
# 安装pytorch

import torch
torch.cuda.is_available()

True

In [6]:
# 基础数据类型
import torch
ndarry1=torch.Tensor(4,5)
ndarry1

NameError: name 'int32' is not defined

In [5]:
# 基础数据类型
import torch
ndarry2=torch.rand(4,5)
ndarry2

tensor([[0.6201, 0.4279, 0.3171, 0.0657, 0.6625],
        [0.8929, 0.0369, 0.2014, 0.7363, 0.3534],
        [0.0015, 0.1736, 0.5160, 0.9122, 0.6848],
        [0.4258, 0.1324, 0.3275, 0.1390, 0.9963]])

In [7]:
# 转numpy
import torch
ndarry3=torch.rand(4,5)
ndarry3.numpy()

array([[0.12083489, 0.94630057, 0.24352503, 0.5717744 , 0.5327178 ],
       [0.08316886, 0.6811492 , 0.40082502, 0.6781628 , 0.02985924],
       [0.09970564, 0.4367131 , 0.4572013 , 0.33369857, 0.79082835],
       [0.7973005 , 0.10356903, 0.38802677, 0.5211268 , 0.47488755]],
      dtype=float32)

In [8]:
# numpy转torch
import torch
import numpy as np
ndarry4=np.random.randn(4,5)
torch.from_numpy(ndarry4)

tensor([[-0.3545, -1.0418,  1.1629, -0.5487,  0.3352],
        [ 1.0793, -0.0622, -0.4029,  0.6274, -0.1968],
        [-0.6175, -0.6202, -0.0541,  1.4951,  1.5021],
        [-0.2440,  1.1561, -0.1268,  0.0592, -0.9575]], dtype=torch.float64)

In [19]:
# 科学计算函数
# 基础数据类型
import torch
import numpy as np
ndarry5=np.random.randint(0,100,size=(4,2))
print(ndarry5)
ndarry5_porch=torch.from_numpy(ndarry5).double()
print(ndarry5_porch)
# 均值函数mean只能用于浮点
torch.mean(ndarry5_porch,1)

[[68 21]
 [75 46]
 [52 75]
 [66 30]]
tensor([[68., 21.],
        [75., 46.],
        [52., 75.],
        [66., 30.]], dtype=torch.float64)


tensor([44.5000, 60.5000, 63.5000, 48.0000], dtype=torch.float64)

In [26]:
# 比较
import torch
a=torch.Tensor([[[1,2],[3,4]]])
b=torch.Tensor([[[1,2],[3,4]]])
c=torch.Tensor([[[1,3],[2,4]]])
print(torch.eq(a,b))
print(torch.equal(a,b))

# 张量比较
print(torch.ge(a,c))
print(torch.gt(a,c))

tensor([[[1, 1],
         [1, 1]]], dtype=torch.uint8)
True
tensor([[[1, 0],
         [1, 1]]], dtype=torch.uint8)
tensor([[[0, 0],
         [1, 0]]], dtype=torch.uint8)
